---
- hosts: nsgvs
  gather_facts: no
  serial: 1
  pre_tasks:
    - name: Check if NSGVs prereq satisfied for predeploy
      include_role:
        name: common
        tasks_from: check-predeploy-prereq
  roles:
    - nsgv-predeploy
