- hosts: vscs
  gather_facts: no
  any_errors_fatal: true
  roles:
    - vsc-health
  vars:
    report_filename: vsc_health_report.txt
    vsc_username: "{{ vsc_custom_username | default(vsc_default_username) }}"
    vsc_password: "{{ vsc_custom_password | default(vsc_default_password) }}"
  serial: 1
