- name: Clean known_hosts of VNSUTILs (ignoring errors)
  known_hosts:
    name: "{{ mgmt_ip }}"
    state: absent
  delegate_to: localhost
  no_log: True
  ignore_errors: True

- name: Wait for VNS Utility VM ssh to be ready
  include_role:
    name: common
    tasks_from: wait-for-ssh
  vars:
    ssh_host: "{{ mgmt_ip }}"
    host_username: "{{ vnsutil_default_username }}"

- block:

  - name: Get vsd node(s) information
    import_role:
      name: common
      tasks_from: vsd-node-info.yml
    vars:
      vsd_hostname: "{{ vsd_fqdn }}"
    run_once: true

  - name: Verify if proxy user is connected to the VSD
    command: /opt/ejabberd/bin/ejabberdctl connected_users
    register: proxy_user
    delegate_to: "{{ vsd_hostname_list[0] }}"
    until: proxy_user.stdout.find('proxy') != -1
    retries: 5
    delay: 30

  # block properties
  remote_user: "{{ vnsutil_default_username }}"
