- block:

  - name: Pull facts on VRS target {{ inventory_hostname }}
    action: setup

  - name: Uninstall Nuage OpenVSwitch package on RedHat OS family distros
    yum: name={{ item }} state=absent
    with_items:
     - openvswitch
     - selinux-policy-nuage
    when: ansible_os_family == "RedHat"

  - name: Uninstall Nuage OpenVSwitch package on Debian OS family distros
    apt: name={{ item }} state=absent purge=yes autoremove=yes
    with_items:
     - nuage-openvswitch-switch
     - nuage-python-openvswitch
     - nuage-openvswitch-common
    when: ansible_os_family == "Debian"

  remote_user: "{{ target_server_username }}"
  become: "{{ 'no' if target_server_username == 'root' else 'yes' }}"
