- block:

  - name: Destroy NSGV VM
    virt:
      name: "{{ vmname }}"
      state: destroyed
      uri: qemu:///system

  - name: Undefine NSGV VM
    virt:
      name: "{{ vmname }}"
      command: undefine
      uri: qemu:///system

  delegate_to: "{{ target_server }}"
  remote_user: "{{ target_server_username }}"
  become: "{{ 'no' if target_server_username == 'root' else 'yes' }}"
