- name: Skip vstat upgrade for versions that do not require upgrade
  include_role:
    name: common
    tasks_from: vstat-upgrade-check.yml

- name: Display if skipping predeploy
  debug:
    msg:
      - "****************************************************"
      - "Skipping VSTAT upgrade because it is not needed"
      - "****************************************************"
  when: skip_vstat_upgrade


- import_tasks: prep_vstat_in_place_upgrade.yml
  remote_user: "{{ vstat_username | default(vstat_default_username) }}"
  become: "{{ 'no' if vstat_username | default(vstat_default_username) == 'root' else 'yes' }}"
  vars:
    ansible_become_pass: "{{ vstat_password | default(vstat_default_password) }}"
  when: not skip_vstat_upgrade
