- name: Clean known_hosts of VSTATs (ignoring errors)
  known_hosts:
    name: "{{ mgmt_ip }}"
    state: absent
  delegate_to: localhost
  no_log: True
  ignore_errors: True

- name: Stat the pid file for elasticsearch process
  stat: path=/var/run/elasticsearch/elasticsearch.pid
  register: pid

- name: Verify that the elasticsearch pid file exists
  assert:
    that: "pid.stat.exists"
    msg: "Pid file for elastic search note found, quiting"

- name: Get status of elasticsearch process
  command: systemctl is-active elasticsearch
  register: es_status

- name: Verify that elasticsearch status is active
  assert:
    that: "es_status.stdout=='active'"
    msg: "Elasticsearch status is {{ es_status.stdout }}, quiting"
