---
- name: Check that from version is set
  assert:
    that: "upgrade_from_version is defined"
    msg: "Upgrade from version is missing"

- name: Check that to version is set
  assert:
    that: "upgrade_to_version is defined"
    msg: "Upgrade to version is missing"

- block:

  - name: Check that VSTAT upgrade scripts path is defined
    assert:
      that: "vstat_upgrade_scripts_path is defined"
      msg: "vstat_upgrade_scripts_path is missing"

  - name: Check that VSTAT upgrade scripts file is defined
    assert:
      that: "vstat_upgrade_scripts_file is defined"
      msg: "vstat_upgrade_scripts_file is missing"

  when: component_type | default("NONE") == 'vstat'

- name: Check that TIM file was found for VSC
  assert:
    that: "vsc_tim_path is defined and vsc_tim_file_name is defined"
    msg: "Missing VSC TIM image file for {{ hostname }} under the unzipped file directory, please unzip it and issue reset_build"
  when: component_type | default("NONE") == 'vsc'
