- name: Get list of partitions
  shell: "guestfish -r -a {{ guestfish_qcow2_path }} run : list-filesystems | grep -Ev '(unknown|swap)'"
  register: partitions_list

- name: Check partition content
  shell: "guestfish -r -a {{ guestfish_qcow2_path }} run : mount {{ item.split(':')[0] }} / : ls /"
  register: partitions
  with_items: "{{ partitions_list.stdout_lines }}"

- name: Find root partition
  set_fact:
    guestfish_mount: "{{ item.item.split(':')[0]}}"
  with_items: "{{ partitions.results }}"
  when: '"proc" in item.stdout'
