- block:

  - name: Set VCIN image location
    include_role:
      name: common
      tasks_from: vsd-find-image.yml

  - name: Verifying VCIN Active/Standby variables
    include_role:
      name: common
      tasks_from: vcin-validate-as-vars
    with_items: "{{ vcins | json_query('[?master_vcin].master_vcin') }}"

  - name: Disable HA deployment for VCIN
    set_fact:
      disable_vcin_ha: True

  - name: Verify VCIN management gateway is in correct IP range
    include_role:
      name: common
      tasks_from: check-ip-in-range.yml
    vars:
      ip_address: "{{ item.mgmt_gateway }}"
      netaddr: "{{ item.mgmt_ip }}"
      netmask: "{{ item.mgmt_ip_prefix }}"
    with_items: "{{ vcins }}"

  - name: Create host_vars files for vcin
    template: src=vsd.j2 backup=no dest={{ inventory_dir }}/host_vars/{{ item.hostname }}
    vars:
      is_vcin: True
    with_items: "{{ vcins }}"

  - name: Re-enabling HA testing based on VSD count
    set_fact:
      disable_vcin_ha: False

  when: vcins is defined and vcins
