- name: Create host_vars files for vrs_vms
  template: src=vrs_vm.j2 backup=no dest={{ playbook_dir }}/host_vars/{{ item.hostname }}
  with_items: "{{ myvrs_vms }}"
  when: myvrs_vms is defined and myvrs_vms
