---
- name: Wait for ssh to be ready
  local_action:
     module: command ssh -oStrictHostKeyChecking=no -oPasswordAuthentication=no {{ host_username }}@{{ ssh_host }} exit 0
  register: wait_for_ssh_output
  until: wait_for_ssh_output.rc == 0
  retries: "{{ retries | default(20) }}"
  delay: "{{ delay | default(10) }}"
